# Generated by Django 4.2.5 on 2023-09-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_condition_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pickup_location',
            new_name='location',
        ),
    ]
