# Generated by Django 4.2.5 on 2023-10-01 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_genre_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_by_owner', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('interested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
